### ISSUE TITLE
Re-add show progress on hover only

### ISSUE THREAD

**Issue by Hampo** [m0bilebtw/skills-tab-progress-bars#12]
Commit https://github.com/m0bilebtw/skills-tab-progress-bars/commit/952ec29a388bdbf6702b5653e62b4743678b9ed6 removed the hover-only setting, which was a setting I used. Could it be re-added?

**Comment by Brandlil** [comment]
I have signed up today just to comment this. The screen is way too cluttered now. That overlay was very useful

**Comment by m0bilebtw** [comment]
Apologies, this feature will be re-added.

**Comment by etc597** [comment]
> Apologies, this feature will be re-added.

Out of curiosity, when can we be expecting the fix? Mostly looking for a rough eta

**Comment by m0bilebtw** [comment]
Rough eta, a few days. Hydrox6 has kindly provided a pull request for it, which I want to find time to test myself before merging, then even when it is merged I need to pull request the plugin-hub repository and have that be accepted by the maintainers for the plugin to actually be updated.

**Comment by m0bilebtw** [comment]
Plugin-hub pull request is here: runelite/plugin-hub#2080
Once that's merged, the update should be available in your RuneLite client
