### ISSUE TITLE
Progress bars randomly aren't visible

### ISSUE THREAD

**Issue by Hampo** [m0bilebtw/skills-tab-progress-bars#14]
Randomly (or without cause as far as I can tell), some of the progress bars aren't visible. Will reappear after the plugin is disabled then enabled. Changing interface tabs doesn't fix it.

Example: Cooking, Prayer, Magic and Fletching aren't visible:
![Not working](https://img.proddy.xyz/Proddy/vud3zxQ.png)
After disable/enable toggle:
![After disable/enable toggle](https://img.proddy.xyz/Proddy/OLvprQD.png)

**Comment by m0bilebtw** [comment]
Not been able to see this for myself - if it happens again and you are able to give more information about exactly what happened before it with logging in/out, changing any plugin/runelite settings, etc etc. that would be appreciated!

**Comment by Hampo** [comment]
I'm pretty sure it's not the thing that caused it originally, but the following steps cause it to happen:

1. Have `Only show when hovered` checked
2. Mouse over a skill to show the progress bar
3. Use a hotkey to change tab
4. Uncheck `Only show when hovered`
5. Check tab back to skills

![Gif](https://img.proddy.xyz/Proddy/JYfYzn2.gif)

**Comment by m0bilebtw** [comment]
I appreciate the clear instructions and video example, but I'm following these steps locally and not getting this issue!
I've tried with my installed runelite (1.8.4), and through my plugin test in IDE on runelite versions 1.8.4 and 1.8.5-SNAPSHOT.

Have you encountered this issue randomly again or only when actively trying to find a way to reproduce like shown above?

**Comment by Hampo** [comment]
Other than the first time, I haven't had it randomly affecting multiple skills again

**Comment by m0bilebtw** [comment]
As I can't reproduce even with the instructions you've shown to reproduce it for you, I'm afraid I can't look further into this. Hopefully the random occurence was a fluke and doesn't return. If it does happen again randomly, or to more people, or if these instructions work for me to reproduce in the future, this issue can be revisited then.
