### ISSUE TITLE
Gray out 200m

### ISSUE THREAD

**Issue by Wiebrendh** [m0bilebtw/skills-tab-progress-bars#17]
Like the option to gray out 99 skills, could there be a function to gray out 200m skills and remove the green progress bar once 200m has been achieved.

![temp](https://user-images.githubusercontent.com/12064383/184895847-7aa23c64-8ef5-4014-8308-70a376dc0727.png)
?

**Comment by m0bilebtw** [comment]
Seems reasonable! Can add when I find time

**Comment by m0bilebtw** [comment]
Seems reasonable! Can add when I find time

**Comment by m0bilebtw** [comment]
Submitted update to plugin hub here: runelite/plugin-hub#3432

**Comment by m0bilebtw** [comment]
Ah I didn't see the 'hide the green progress bar' - that will be separate later on

**Comment by m0bilebtw** [comment]
This update should now be live in the plugin hub!
