### ISSUE TITLE
the plugin stopped working

### ISSUE THREAD

**Issue by starryskies2** [m0bilebtw/skills-tab-progress-bars#18]
after recent update jagex did at 3.15.23 the plugin stopped working and isnt visible in the pluging hub/runelite

**Comment by m0bilebtw** [comment]
Yep, runelite API has changed and I don't have time to fix the plugin until tonight so hold tight for now

**Comment by starryskies2** [comment]
thank you guys i appricate it alot!!amazing how quick you guys fixed it

**Comment by m0bilebtw** [comment]
This has now been accepted into the hub - restart clients and it should be good to go
