### ISSUE TITLE
Feature Request: Option to start and end bars at indent

### ISSUE THREAD

**Issue by iawhd** [m0bilebtw/skills-tab-progress-bars#2]
Hey, Love the plugin! 

Would it be possible for you to add an option where the progress bars start in line with the indent (Red arrows below) instead of the edge (Blue arrows).

I appreciate it's a weird request but it's kinda an OCD thing for me :)

![image](https://user-images.githubusercontent.com/29826207/77828001-05911b80-7111-11ea-9472-48410ff409fc.png)

**Comment by m0bilebtw** [comment]
I had considered this, and seeing as I'm not the only one who thought of
it, I'll implement this for the next release! No promises on when that will
be though

**Comment by iawhd** [comment]
Thanks man!

**Comment by m0bilebtw** [comment]
This update has now been accepted into plugin hub so should be active when you next open RuneLite!

**Comment by iawhd** [comment]
Got it! Looks way better now, thanks!
