### ISSUE TITLE
Darken skills at 200m xp

### ISSUE THREAD

**Issue by d0dddd** [m0bilebtw/skills-tab-progress-bars#20]
Darken skills at 200m xp not working

**Comment by m0bilebtw** [comment]
Are you able to check your runelite client logs to see if there's anything relevant in there? Unfortunately I don't have a 200m skill to test with

**Comment by d0dddd** [comment]
No worries. Thanks for speedy reply. I don't see anything in client logs but have a friend double checking. Will report back.

**Comment by m0bilebtw** [comment]
Thanks! Could you also confirm if the darken at 99 is broken for you too or only the 200m?

**Comment by d0dddd** [comment]
We don't see anything out of the ordinary. Darken at 99 works just fine. I apologize for not having more info

**Comment by m0bilebtw** [comment]
Alright, I'll try to play around with it but probably won't be able to for a few days

**Comment by m0bilebtw** [comment]
Does the problem persist if you toggle the darken at 200m or darken at 99 settings?
Also try changing the darken skill opacity and see if that makes a difference.
Can't see why it would be working for 99 but failing for 200m as it uses the same code path to do the darkening, and the 200m check seems fine

**Comment by d0dddd** [comment]
https://github.com/m0bilebtw/skills-tab-progress-bars/assets/162522239/33d46c9a-15bc-4dd8-b997-f12b062fa712

**Comment by d0dddd** [comment]
https://github.com/m0bilebtw/skills-tab-progress-bars/assets/162522239/087fb5dc-0fc3-4d12-8ade-1cb73f653cd8

**Comment by d0dddd** [comment]
https://github.com/m0bilebtw/skills-tab-progress-bars/assets/162522239/d6bfa655-ac0d-4e64-b602-af50c5393c87

**Comment by lmyw** [comment]
I don't know how to check client logs, but I'm also having the same issue. Darken 99s is working perfectly and the 200m xp skill will also darken itself if that option is ticked, but trying to use the 200m xp tickbox itself doesn't work.

**Comment by m0bilebtw** [comment]
I can't figure out why this would be happening - the code seems sound to me. Will leave the issue open in case anyone with a 200m is able to run the plugin in dev mode and do some debugging as I don't have a 200m to test with.

**Comment by lmyw** [comment]
i have a 200m, i'd be happy to help out in any way i can

**Comment by m0bilebtw** [comment]
Hi @lmyw Would you be able to screen record with your skills panel in view, as well as the plugin settings - while toggling the darken 99 and 200m settings so I can see exactly what you mean by your earlier comment?

**Comment by lmyw** [comment]
https://github.com/user-attachments/assets/5a6f9698-3636-4135-b3f3-d6b0ffdd4147

**Comment by m0bilebtw** [comment]
I have found the mistake and submitted an update to fix it - will update thread when that update is available for you to confirm!

**Comment by lmyw** [comment]
works perfectly!

**Comment by m0bilebtw** [comment]
Awesome, thanks for the help on this!
