### ISSUE TITLE
Other Darken Options

### ISSUE THREAD

**Issue by loegare** [m0bilebtw/skills-tab-progress-bars#22]
I loved the darken at 99 while i was maxing, and now that i am, darken at 200m just doesnt have the same ring as thats so far away. 

could something like darken at '___' xp or darken over min level be added?

**Comment by Committing** [comment]
+1 this is exactly what I'm looking for. Darken at X level

**Comment by syrifgit** [comment]
Would be great for leagues to have options to darken at 50m exp too!

**Comment by m0bilebtw** [comment]
I've submitted an update to plugin hub, runelite/plugin-hub#7181

This reworks the darken options to have easy 99 or 200m options, as well as completely custom options by level or by xp that both include the virtual level ranges. It also adds the option to hide progress and/or goal bars specifically on darkened skills.

For those with 200m, please be aware that the progress bars still showing at 200m was _a bug_. However, I know you may be used to this behaviour, so I've added a toggle if you would like to "Still show at 200m".

**Comment by m0bilebtw** [comment]
The update has been accepted so I'm closing this issue - I've been able to test it in leagues so fairly confident it works but if there are any problems with it please do let me know via this or another issue!

**Comment by Committing** [comment]
> The update has been accepted so I'm closing this issue - I've been able to test it in leagues so fairly confident it works but if there are any problems with it please do let me know via this or another issue!

Amazing update tysm
