### ISSUE TITLE
Plugin seems to do nothing on initial install

### ISSUE THREAD

**Issue by Hydrox6** [m0bilebtw/skills-tab-progress-bars#3]
When I first used the plugin, I was kinda annoyed that it only seemed to show a bar for the skill I was training. Later, when I reinstalled, it didn't show a bar for any skill.

You'll want to add some code to `startUp` to get all the current XP values and make the bars from that. That way, people who install the plugin whilst logged in don't get confused and potentially not use a really cool plugin.

**Comment by m0bilebtw** [comment]
A very good point I'd overlooked. What's happening currently is I'm
listening to any changes in xp, which come through when a player logs in as
well as when a player gains any xp, and had left it at that not thinking
about when a user is already logged in upon installation. Thanks for
bringing this up, will sort this out soon.
