### ISSUE TITLE
Add an option to track level targets instead of or in addition to current levels.

### ISSUE THREAD

**Issue by brainard52** [m0bilebtw/skills-tab-progress-bars#4]
First, I think this is one of my favorite plugins. Thanks so much for your work.

I think it would be really cool if the bars could represent level targets rather than just progress. Perhaps both could be included if the horizontal bar was actually two horizontal bars stacked up.

**Comment by svidovich** [comment]
In addition please. I'm enjoying this plugin _because_ it doesn't go to targets.

**Comment by m0bilebtw** [comment]
This update has now been accepted into the plugin hub - check plugin hub or restart runelite to update the plugin and try it out! Let me know if there are any issues with it.

[Accepted pr here](https://github.com/runelite/plugin-hub/pull/302)
