### ISSUE TITLE
Add custom progress bar colours

### ISSUE THREAD

**Issue by svidovich** [m0bilebtw/skills-tab-progress-bars#5]
As a RuneLite skills tab progress bars user, I want to be able to change the colour gradient of the progress bar, because that would be sick and dope.

**Comment by m0bilebtw** [comment]
Would you be looking for a static custom colour for bar? Custom start/end colours for the fade as you progress through a level? Or the bar to display a gradient across itself at one single time (eg. the left be red, transitioning to green on the right)?

This isn't particularly high priority but I'm not ruling it out.

**Comment by svidovich** [comment]
I had custom start/end colours for the fade as progression occurred in mind, but all of those sound amazing!

**Comment by m0bilebtw** [comment]
I'd probably only look to implement one colour customisation, so the bar would, at any one time, be a single colour - but you'd choose the colour it would fade from and to as xp increases.

**Comment by svidovich** [comment]
That sounds fabulous!
