### ISSUE TITLE
Add support for virtual levels

### ISSUE THREAD

**Issue by Hydrox6** [m0bilebtw/skills-tab-progress-bars#6]
Would be nice to know how far I am away from a virtual level, even if you can't see them in vanilla.

**Comment by m0bilebtw** [comment]
This update has now been accepted into the plugin hub - check plugin hub or restart runelite to update the plugin and try it out! Let me know if there are any issues with it.

[Accepted pr here](https://github.com/runelite/plugin-hub/pull/302)
