### ISSUE TITLE
Option to not hide other bars when hovering

### ISSUE THREAD

**Issue by yani** [m0bilebtw/skills-tab-progress-bars#7]
I don't mind all bars to be visible when hovering over the skills.

Could it be possible to add an option for this?

**Comment by m0bilebtw** [comment]
The problem with showing the progress bars when hovering skills is that the in-game tooltip showing current XP, next level XP, etc. is covered by the bars of other skills. 

I need to tell runelite on which layer to draw this overlay, and there exists no layer that is above the skills themselves but beneath the tooltips. As such, the bars get in the way of reading the tooltips. This was first discussed in issue #1 if you're interested. The ideal solution would be runelite to add a layer that would be between the skill widgets and the tooltip widget that shows on hover, but when I asked they had no intention of doing this.

Given that the bars absolutely would be in-front of the skill hover tooltips looking messy, and sometimes making reading the tooltip text difficult depending on settings, is this still a toggle you really want?

**Comment by yani** [comment]
I thought about that as well, but I did not know you looked this hard into it. Do you think it's possible to change the layer of the hover info itself, as a workaround? I can't look that much into it myself right now. 

Or maybe having a list of what skill is being hovered and what exp bars are behind the hover info to hide only those?

**Comment by m0bilebtw** [comment]
I don't think changing the layer of the tooltip with xp info is feasible, but I'd be happy to be proven wrong.

Accounting for the specific skills that are covered by other skills tooltips would be somewhat messy - to support changing settings, maxed and non-maxed skills, etc. each skill would need a corresponding collection of 3 to 6 other skills, which would need to be checked every time the overlay is drawn while any one skill is being hovered. It's possible, but seems messy, inefficient, not necessarily worth the benefit of simply having fewer bars hide when hovering a skill.

I'm not saying it won't happen, or that there isn't some other better solution, just that I'm not confident it's a good thing to do yet.

**Comment by prxsto** [comment]
I'm wondering if the opposite is possible: is it possible to add a toggle so that it only shows the visual progress bar for a specific skill when hovered?

**Comment by m0bilebtw** [comment]
That's doable for sure, separate to this issue. Will implement soon.

**Comment by m0bilebtw** [comment]
> I'm wondering if the opposite is possible: is it possible to add a toggle so that it only shows the visual progress bar for a specific skill when hovered?
@prxsto 
Have updated the plugin, will be submitting the update to plugin-hub shortly, where there is a toggle which when enabled will only show progress bar for the skill you are currently hovering. This does not affect this issue though, still no ideal solution.
